variables:
  # App Specifications
  MIN_CPU: 150m
  MIN_MEMORY: 200Mi
  MAX_CPU: 350m
  MAX_MEMORY: 400Mi
  PORT: 8000
  PROXY_BODY_SIZE: 5m #5 Megabyte

  # Image and Deployment Variables, It's better to not change these variables below
  # because they are used in the deploy script
  VERSION: $CI_COMMIT_TAG
  TAG_IMAGE_NAME: "$registry_host/$CI_PROJECT_PATH:$VERSION"
  APP_NAME: "$CI_PROJECT_NAME"
  INGRESS_HOST: "$CI_PROJECT_PATH_SLUG"

  # App Variables, you can add your own variables here
  # App variables must have the prefix "PODS_" or "NEXT_PUBLIC_"
  PODS_TEST: tests
  PODS_TESTNUM: 12312312
  PODS_TESTEQ: 123123=12312312
  NEXT_PUBLIC_TEST: true

  PODS_SECRET_KEY: "$PODS_SECRET_KEY"
  PODS_DEBUG: "$PODS_DEBUG"
  PODS_ALLOWED_HOSTS: "$PODS_ALLOWED_HOSTS"
  PODS_DJANGO_LOGLEVEL: "$PODS_DJANGO_LOGLEVEL"
  PODS_DATABASE_ENGINE: "$PODS_DATABASE_ENGINE"
  PODS_DB_SCHEMA: "$PODS_DB_SCHEMA"
  PODS_AUTH_SERVICE_URL: "$PODS_AUTH_SERVICE_URL"
