# Generated by Django 5.1.6 on 2025-03-18 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineQuantity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('needed_qty', models.IntegerField()),
                ('fulfilled_qty', models.IntegerField(default=0)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('total_price', models.IntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ON PROCESS', 'On Process'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.UUIDField()),
                ('medicines', models.ManyToManyField(through='prescription.MedicineQuantity', to='medicine.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_price', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='medicinequantity',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescription.prescription'),
        ),
        migrations.AddConstraint(
            model_name='medicinequantity',
            constraint=models.CheckConstraint(condition=models.Q(('needed_qty__gte', models.F('fulfilled_qty'))), name='fulfilled_qty_lte_needed_qty'),
        ),
        migrations.AddConstraint(
            model_name='medicinequantity',
            constraint=models.CheckConstraint(condition=models.Q(('fulfilled_qty__gte', 1)), name='fulfilled_qty_gte_1'),
        ),
    ]
