# Generated by Django 5.1.6 on 2025-03-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_medicine_deleted_at'),
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='prescription',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['deleted_at'], name='prescriptio_deleted_a3929d_idx'),
        ),
    ]
