# Generated by Django 5.1.6 on 2025-03-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_medicine_deleted_at'),
        ('prescription', '0002_rename_created_date_prescription_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicinequantity',
            name='fulfilled_qty_lte_needed_qty',
        ),
        migrations.RemoveConstraint(
            model_name='medicinequantity',
            name='fulfilled_qty_gte_1',
        ),
        migrations.AddConstraint(
            model_name='medicinequantity',
            constraint=models.CheckConstraint(condition=models.Q(('needed_qty__gte', 1)), name='needed_qty_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='medicinequantity',
            constraint=models.CheckConstraint(condition=models.Q(('fulfilled_qty__gte', 0)), name='fulfilled_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='medicinequantity',
            constraint=models.CheckConstraint(condition=models.Q(('fulfilled_qty__lte', models.F('needed_qty'))), name='fulfilled_qty_lte_needed_qty'),
        ),
    ]
