# Generated by Django 5.1.6 on 2025-03-28 08:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_remove_medicinequantity_fulfilled_qty_lte_needed_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ON PROCESS', 'On Process'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled'), ('PAID', 'Paid')], default='CREATED', max_length=20),
        ),
    ]
