# Generated by Django 5.1.6 on 2025-03-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
